FROM continuumio/miniconda3:4.5.11

USER root
ARG username
RUN useradd --create-home --home-dir /home/${username} ${username}
ENV HOME /home/${username}

RUN apt-get update && apt-get install -y build-essential
RUN apt-get install texlive-xetex -y

RUN conda install nb_conda_kernels -y
RUN conda install -c bioconda snakemake -y

COPY docker/environment.yml ${HOME}/envs/
RUN conda env create -f ${HOME}/envs/environment.yml
RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
RUN echo "${HOME}/lib" >> /opt/conda/envs/scibase/lib/python3.6/site-packages/mylib.pth

# switch to newly created user to avoid running container as root
WORKDIR $HOME
USER ${username}

COPY docker/startup.sh . 
