#!/bin/sh
# Precommit script backs up conda environment
# Install in the hooks folder with: ln -s ../../pre-commit .git/hooks/pre-commit

echo "exporting current environment to environment.yml..."
conda env export > python/environment.yml
echo "..and adding the change to your commit.."
git add python/environment.yml

echo "precommit complete"